version: '3.7'

services:
  build_and_publish:
    build:
      context: docker
      dockerfile: Dockerfile
      args:
        PYPI_TOKEN: ${PYPI_TOKEN}
        LIB_VERSION: ${LIB_VERSION}
    volumes:
      - ./:/src/
  test:
    build:
      context: docker
      dockerfile: Dockerfile.test
    volumes:
      - ./:/src/